ALTER POLICY "fund_allocations_select" ON "fund_allocations" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_allocations.read'));--> statement-breakpoint
ALTER POLICY "fund_allocations_insert" ON "fund_allocations" TO app_runtime WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_allocations.manage'));--> statement-breakpoint
ALTER POLICY "fund_commitments_select" ON "fund_commitments" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_commitments.read'));--> statement-breakpoint
ALTER POLICY "fund_commitments_insert" ON "fund_commitments" TO app_runtime WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_commitments.manage'));--> statement-breakpoint
ALTER POLICY "fund_commitments_update" ON "fund_commitments" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_commitments.manage')) WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_commitments.manage'));--> statement-breakpoint
ALTER POLICY "fund_disbursements_select" ON "fund_disbursements" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_disbursements.read'));--> statement-breakpoint
ALTER POLICY "fund_disbursements_insert" ON "fund_disbursements" TO app_runtime WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_disbursements.post'));--> statement-breakpoint
ALTER POLICY "fund_disbursements_update" ON "fund_disbursements" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_disbursements.reverse')) WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_disbursements.reverse'));--> statement-breakpoint
ALTER POLICY "fund_ledger_entries_select" ON "fund_ledger_entries" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_ledger.read'));--> statement-breakpoint
ALTER POLICY "fund_receipts_select" ON "fund_receipts" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_receipts.read'));--> statement-breakpoint
ALTER POLICY "fund_receipts_insert" ON "fund_receipts" TO app_runtime WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_receipts.post'));--> statement-breakpoint
ALTER POLICY "fund_receipts_update" ON "fund_receipts" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_receipts.reverse')) WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_receipts.reverse'));--> statement-breakpoint
ALTER POLICY "fund_reconciliations_select" ON "fund_reconciliations" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_reconciliations.read'));--> statement-breakpoint
ALTER POLICY "fund_reconciliations_insert" ON "fund_reconciliations" TO app_runtime WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_reconciliations.manage'));--> statement-breakpoint
ALTER POLICY "fund_restrictions_select" ON "fund_restrictions" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_restrictions.read'));--> statement-breakpoint
ALTER POLICY "fund_restrictions_insert" ON "fund_restrictions" TO app_runtime WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_restrictions.manage'));--> statement-breakpoint
ALTER POLICY "fund_restrictions_update" ON "fund_restrictions" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_restrictions.manage')) WITH CHECK (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_restrictions.manage'));--> statement-breakpoint
ALTER POLICY "fund_reversals_select" ON "fund_reversals" TO app_runtime USING (private.has_active_membership(organization_id) and private.has_permission(organization_id, 'fund_ledger.read'));