ALTER POLICY audit_events_insert ON public.audit_events
  WITH CHECK (
    private.has_active_membership(organization_id)
    AND (
      private.has_permission(organization_id, 'applications.manage')
      OR private.has_permission(organization_id, 'applications.submit')
      OR private.has_permission(organization_id, 'applications.screen')
      OR private.has_permission(organization_id, 'applications.convert')
      OR private.has_permission(organization_id, 'cases.manage')
      OR private.has_permission(organization_id, 'cases.assign')
      OR private.has_permission(organization_id, 'assessment_templates.manage')
      OR private.has_permission(organization_id, 'assessment_templates.publish')
      OR private.has_permission(organization_id, 'assessments.manage')
      OR private.has_permission(organization_id, 'assessments.submit')
      OR private.has_permission(organization_id, 'assessments.review')
      OR private.has_permission(organization_id, 'approval_workflows.manage')
      OR private.has_permission(organization_id, 'approval_workflows.publish')
      OR private.has_permission(organization_id, 'approval_requests.create')
      OR private.has_permission(organization_id, 'approval_requests.submit')
      OR private.has_permission(organization_id, 'approval_requests.act')
      OR private.has_permission(organization_id, 'approval_requests.cancel')
      OR private.has_permission(organization_id, 'fund_restrictions.manage')
      OR private.has_permission(organization_id, 'fund_commitments.manage')
      OR private.has_permission(organization_id, 'fund_receipts.post')
      OR private.has_permission(organization_id, 'fund_receipts.reverse')
      OR private.has_permission(organization_id, 'fund_allocations.manage')
      OR private.has_permission(organization_id, 'fund_allocations.activate')
      OR private.has_permission(organization_id, 'fund_allocations.reverse')
      OR private.has_permission(organization_id, 'fund_disbursements.post')
      OR private.has_permission(organization_id, 'fund_disbursements.reverse')
      OR private.has_permission(organization_id, 'fund_reconciliations.manage')
      OR private.has_permission(organization_id, 'distributions.manage')
      OR private.has_permission(organization_id, 'distributions.ready')
      OR private.has_permission(organization_id, 'distributions.assign')
      OR private.has_permission(organization_id, 'distributions.execute')
      OR private.has_permission(organization_id, 'distributions.confirm')
      OR private.has_permission(organization_id, 'distributions.verify')
      OR private.has_permission(organization_id, 'distributions.complete')
      OR private.has_permission(organization_id, 'distributions.cancel')
      OR private.has_permission(organization_id, 'distribution_evidence.manage')
      OR private.has_permission(organization_id, 'programs.manage')
      OR private.has_permission(organization_id, 'aid_package_packings.manage')
    )
  );
