/**
 * Label hak akses berbahasa Indonesia, dikelompokkan sesuai menu aplikasi
 * agar admin mudah memahami apa yang diberikan pada setiap peran.
 */
export const permissionModules: Array<{ label: string; resources: string[] }> = [
  { label: "Lapangan", resources: ["field_tasks", "field_reports", "field_settings"] },
  {
    label: "Penghimpunan",
    resources: [
      "donors",
      "fund_ledger",
      "fund_receipts",
      "fund_commitments",
      "fund_restrictions",
      "fund_allocations",
      "fund_disbursements",
      "fund_reconciliations",
      "in_kind_donations",
      "waqf",
      "waqf_assets",
      "waqf_contributions",
      "waqf_income",
      "waqf_benefits",
      "waqf_utilizations",
      "waqf_valuations",
      "waqf_maintenance",
      "waqf_legal_documents",
      "waqf_nazhir",
      "kafalah",
      "kafalah_needs",
      "kafalah_matches",
      "kafalah_contracts",
      "kafalah_payments",
      "kafalah_distributions",
      "kafalah_monitoring",
      "kafalah_renewals",
    ],
  },
  {
    label: "Program & pengajuan",
    resources: [
      "programs",
      "program_categories",
      "program_goods_plan",
      "program_revisions",
      "applications",
      "waqf_proposals",
      "cases",
      "assessments",
      "assessment_templates",
      "approval_requests",
      "approval_workflows",
    ],
  },
  {
    label: "Penyaluran",
    resources: [
      "distributions",
      "distribution_evidence",
      "aid_package_templates",
      "aid_package_packings",
      "logistics_shipments",
      "logistics_couriers",
      "logistics_incidents",
      "inventory_products",
      "inventory_product_categories",
      "inventory_warehouses",
      "inventory_balances",
      "inventory_batches",
      "inventory_movements",
      "inventory_adjustments",
      "procurement_requests",
      "purchase_orders",
      "goods_receipts",
      "vendor_invoices",
      "evidence_files",
      "evidence_audit",
    ],
  },
  {
    label: "Relasi (kontak & penerima)",
    resources: [
      "crm_contacts",
      "crm_contact_roles",
      "crm_beneficiary_profiles",
      "crm_institution_profiles",
      "crm_sensitive_identities",
      "crm_interactions",
      "crm_consents",
      "crm_tags",
      "crm_contact_tags",
      "crm_duplicate_candidates",
      "crm_merge_requests",
    ],
  },
  {
    label: "Laporan & pengawasan",
    resources: ["reports", "stakeholder_reports", "audit", "risk_flags", "governance_incidents", "complaints", "corrective_actions"],
  },
  {
    label: "Tata kelola",
    resources: ["organizations", "organization_units", "organization_relationships", "memberships", "roles"],
  },
];

export const resourceLabels: Record<string, string> = {
  aid_package_packings: "Pengemasan paket",
  aid_package_templates: "Template paket bantuan",
  applications: "Pengajuan bantuan",
  approval_requests: "Permintaan approval",
  approval_workflows: "Workflow approval",
  assessment_templates: "Template asesmen",
  assessments: "Asesmen",
  audit: "Jejak audit",
  cases: "Kasus penerima",
  complaints: "Pengaduan",
  corrective_actions: "Tindakan perbaikan",
  crm_beneficiary_profiles: "Profil penerima manfaat",
  crm_consents: "Persetujuan (consent)",
  crm_contact_roles: "Peran kontak",
  crm_contact_tags: "Tag pada kontak",
  crm_contacts: "Kontak",
  crm_duplicate_candidates: "Kandidat kontak ganda",
  crm_institution_profiles: "Profil lembaga",
  crm_interactions: "Catatan komunikasi",
  crm_merge_requests: "Penggabungan kontak",
  crm_sensitive_identities: "Identitas sensitif (NIK/KK)",
  crm_tags: "Master tag",
  distribution_evidence: "Bukti penyaluran",
  distributions: "Distribusi",
  donors: "Donatur & wakif",
  evidence_audit: "Audit akses bukti",
  evidence_files: "Berkas bukti",
  field_reports: "Laporan lapangan",
  field_settings: "Pengaturan lapangan",
  field_tasks: "Tugas lapangan",
  fund_allocations: "Alokasi dana",
  fund_commitments: "Janji donasi",
  fund_disbursements: "Pencairan dana",
  fund_ledger: "Buku besar dana",
  fund_receipts: "Penerimaan dana",
  fund_reconciliations: "Rekonsiliasi",
  fund_restrictions: "Pos dana terikat",
  goods_receipts: "Penerimaan barang (pengadaan)",
  governance_incidents: "Insiden",
  in_kind_donations: "Donasi barang",
  inventory_adjustments: "Penyesuaian stok",
  inventory_balances: "Saldo stok",
  inventory_batches: "Batch stok",
  inventory_movements: "Mutasi stok",
  inventory_product_categories: "Kategori produk",
  inventory_products: "Produk inventory",
  inventory_warehouses: "Gudang",
  kafalah: "Kafalah",
  kafalah_contracts: "Kontrak kafalah",
  kafalah_distributions: "Penyaluran kafalah",
  kafalah_matches: "Pencocokan kafil",
  kafalah_monitoring: "Monitoring kafalah",
  kafalah_needs: "Kebutuhan kafalah",
  kafalah_payments: "Pembayaran kafalah",
  kafalah_renewals: "Perpanjangan kafalah",
  logistics_couriers: "Kurir",
  logistics_incidents: "Insiden logistik",
  logistics_shipments: "Pengiriman",
  memberships: "Anggota",
  organization_relationships: "Relasi antar-organisasi",
  organization_units: "Unit organisasi",
  organizations: "Profil organisasi",
  procurement_requests: "Permintaan pengadaan",
  program_categories: "Kategori program",
  program_goods_plan: "Rencana barang program",
  program_revisions: "Riwayat revisi program",
  programs: "Program",
  purchase_orders: "Pesanan pembelian",
  reports: "Laporan & dashboard",
  risk_flags: "Risiko",
  roles: "Peran & hak akses",
  stakeholder_reports: "Laporan per donatur & mitra",
  vendor_invoices: "Tagihan vendor",
  waqf: "Wakaf",
  waqf_assets: "Aset wakaf",
  waqf_benefits: "Penyaluran manfaat wakaf",
  waqf_contributions: "Setoran wakif",
  waqf_income: "Hasil wakaf",
  waqf_legal_documents: "Dokumen legal wakaf",
  waqf_maintenance: "Pemeliharaan aset wakaf",
  waqf_nazhir: "Nazhir",
  waqf_proposals: "Pengajuan program wakaf",
  waqf_utilizations: "Pemanfaatan wakaf",
  waqf_valuations: "Penilaian aset wakaf",
};

export const actionLabels: Record<string, string> = {
  act: "Memutuskan",
  activate: "Mengaktifkan",
  approve: "Menyetujui",
  assign: "Menugaskan",
  cancel: "Membatalkan",
  complete: "Menyelesaikan",
  confirm: "Mengonfirmasi",
  convert: "Mengonversi",
  create: "Membuat",
  decide: "Memutuskan",
  delete: "Menghapus",
  deliver: "Serah terima",
  dispatch: "Memberangkatkan",
  distribute: "Menyalurkan",
  download: "Mengunduh",
  execute: "Melaksanakan",
  issue: "Menerbitkan",
  manage: "Mengelola",
  pack: "Mengemas",
  post: "Membukukan",
  publish: "Menerbitkan",
  read: "Melihat",
  ready: "Menandai siap",
  receive: "Menerima",
  record: "Mencatat",
  register: "Mendaftarkan",
  report: "Melaporkan",
  resolve: "Menyelesaikan",
  restricted_read: "Melihat data terbatas",
  return: "Retur",
  reverse: "Membatalkan (reversal)",
  review: "Mereview",
  screen: "Menyeleksi",
  submit: "Mengajukan",
  track: "Melacak",
  unpack: "Membongkar",
  upload: "Mengunggah",
  verify: "Memverifikasi",
};

export function resourceLabel(resource: string) {
  return resourceLabels[resource] ?? resource.replaceAll("_", " ");
}

export function actionLabel(action: string) {
  return actionLabels[action] ?? action.replaceAll("_", " ");
}
