import fs from "node:fs";
import path from "node:path";
import { createPool, workspaceRoot } from "./shared.mjs";

const typeMap = new Map([
  ["boolean", "boolean"],
  ["integer", "number"],
  ["bigint", "number"],
  ["numeric", "string"],
  ["real", "number"],
  ["double precision", "number"],
  ["uuid", "string"],
  ["text", "string"],
  ["character varying", "string"],
  ["timestamp with time zone", "string"],
  ["timestamp without time zone", "string"],
  ["date", "string"],
  ["json", "unknown"],
  ["jsonb", "unknown"],
]);

function toPascalCase(value) {
  return value
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

const pool = createPool({ direct: true });

try {
  const result = await pool.query(`
    select
      table_name,
      column_name,
      data_type,
      is_nullable
    from information_schema.columns
    where table_schema = 'public'
      and table_name <> 'schema_migrations'
    order by table_name, ordinal_position
  `);

  const tables = new Map();

  for (const row of result.rows) {
    if (!tables.has(row.table_name)) {
      tables.set(row.table_name, []);
    }

    tables.get(row.table_name).push(row);
  }

  const lines = [
    "// Generated by npm run neon:types. Do not edit manually.",
    "",
    "export type JsonValue = unknown;",
    "",
    "export interface Database {",
    "  public: {",
    "    Tables: {",
  ];

  for (const tableName of tables.keys()) {
    lines.push(`      ${tableName}: {`);
    lines.push(`        Row: ${toPascalCase(tableName)}Row;`);
    lines.push("      };");
  }

  lines.push("    };");
  lines.push("  };");
  lines.push("}");
  lines.push("");

  for (const [tableName, columns] of tables) {
    lines.push(`export interface ${toPascalCase(tableName)}Row {`);

    for (const column of columns) {
      const tsType = typeMap.get(column.data_type) ?? "unknown";
      const nullable = column.is_nullable === "YES" ? " | null" : "";
      lines.push(`  ${column.column_name}: ${tsType}${nullable};`);
    }

    lines.push("}");
    lines.push("");
  }

  const outputDir = path.join(workspaceRoot, "src", "generated", "neon");
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(path.join(outputDir, "database.ts"), `${lines.join("\n")}\n`);

  console.log(`Types Neon dibuat untuk ${tables.size} tabel.`);
} finally {
  await pool.end();
}
